# Copyright Spack Project Developers. See COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack_repo.builtin.build_systems.cmake import CMakePackage

from spack.package import *


class MfemMgis(CMakePackage):
    """MFEM/MGIS is a C++ library to build advanced mechanical simulations
    based on MFront behaviours with MFEM. It relies on MGIS to load and
    integrate the behaviours generated by MFront."""

    homepage = "https://thelfer.github.io/mfem-mgis/"
    url = "https://github.com/thelfer/mfem-mgis/archive/refs/tags/v1.0.4.tar.gz"
    git = "https://github.com/thelfer/mfem-mgis.git"

    maintainers("thelfer", "rprat-pro", "trsxvz")

    license("LGPL-3.0-only")

    version("master", branch="master")
    version("1.0.4", sha256="d37bc29dd9e962db9cbc6b3c2deb901ac60f0422f20d4e30941fd5275b5eca4c")
    version("1.0.3", sha256="41c03234e5916ce7dedf3c4beeb0f34abed3f50e93761ebc2a086d380cca18cd")
    version("1.0.2", sha256="a2d235c36de0d37f7ed10069a4b694c73a7e4f79a7360b6fb952864f5d3cc611")
    version("1.0.1", sha256="74f0d4d1ecbb3a8a152289899eda5be6ab45c4735d44a58ec2db3a6b2fd7b97b")

    variant("mumps", default=True, description="Enable the MUMPS solver in MFEM")
    variant("miniapps", default=True, description="Build and install the MFEM miniapps")
    variant("int64", default=True, description="Use 64-bit integers in hypre and metis")

    depends_on("c", type="build")
    depends_on("cxx", type="build")

    depends_on("mpi")
    depends_on("mfem@4.8:+mpi+suite-sparse")
    depends_on("mfem+mumps", when="+mumps")
    depends_on("mfem~mumps", when="~mumps")
    depends_on("mfem+miniapps", when="+miniapps")
    depends_on("mfem~miniapps", when="~miniapps")
    depends_on("hypre")
    depends_on("hypre+int64", when="+int64")
    depends_on("hypre~int64", when="~int64")
    depends_on("metis+int64", when="+int64")
    depends_on("metis~int64", when="~int64")
    depends_on("mgis+c~fortran~python")
    depends_on("mgis@master+mgis-function", when="@master")
    depends_on("mgis@snapshot-for-mfemmgis-1.0.4", when="@1.0.4")
    depends_on("mgis@3.1.0+mgis-function", when="@1.0.3")
    depends_on("mgis@3.0.2", when="@1.0.2")
    depends_on("mgis@snapshot-for-mfemmgis-1.0.1", when="@1.0.1")
    depends_on("tfel", type=("build", "link", "run"))

    # missing include in a test, fixed upstream after the 1.0.1 release
    patch(
        "https://github.com/thelfer/mfem-mgis/commit/942dc5e9bd6de7535e466f13f93cdcbb53b6f414.patch?full_index=1",
        sha256="0dbe4caf30a6de49addfd7bbc3eabf9bab5ea8bd3b9ca30c4eb73acffa566c1a",
        when="@1.0.1",
    )

    def setup_run_environment(self, env: EnvironmentModifications) -> None:
        env.set("MFEMMGIS_DIR", join_path(self.prefix.share, "mfem-mgis", "cmake"))

    def check(self):
        """skip target 'test' which doesn't build the test programs used by tests"""
        with working_dir(self.build_directory):
            if self.generator == "Unix Makefiles":
                self._if_make_target_execute("check")
            elif self.generator == "Ninja":
                self._if_ninja_target_execute("check")

    def cmake_args(self):
        return [
            self.define("USE_EXTERNAL_COMPILER_FLAGS", True),
            self.define("CMAKE_POSITION_INDEPENDENT_CODE", True),
            self.define("MFrontGenericInterface_DIR", self.spec["mgis"].prefix.share.mgis.cmake),
            self.define("TFEL_DIR", self.spec["tfel"].prefix.share.tfel.cmake),
            self.define("HYPRE_DIR", self.spec["hypre"].prefix),
        ]
